// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmhnvulpmaxhhxhivtur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtaG52dWxwbWF4aGh4aGl2dHVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMzQyNzEsImV4cCI6MjA3MDkxMDI3MX0.PWXxSgWEJjzwAD5k2PZh37gL_JRsHYx0NdDK6q2mjbU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});